dist: xenial
language: node_js
node_js:
- stable
cache:
  directories:
  - "./node_modules"
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- npm install -g gulp-cli
- npm install node-sass@4.12.0
- npm install
install:
- gem install jekyll
- gem install bundler
- bundle update
script:
- node --max_old_space_size=9048 ./node_modules/gulp/bin/gulp.js build
- node ./node_modules/gulp/bin/gulp.js jekyll
deploy:
- provider: script
  skip_cleanup: true
  script: rsync -r -e 'ssh -p 4444' --quiet --exclude 'src' --exclude 'deploy_rsa.enc'
    --exclude 'README.md' --exclude 'package.json' --exclude 'gulpfile.js' --exclude
    '.gitignore' --exclude 'node_modules' --exclude 'package-lock.json' $TRAVIS_BUILD_DIR/_site/
    floris@fmjansen.com:/var/www/inclusief.design/
  on:
    branch: main
addons:
  ssh_known_hosts: fmjansen.com:4444
before_deploy:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
